app:
  kafka:
    consumer:
      timeout: 10

  version: 1.0

redis:
  host: host
  port: 123

spring:
  threads:
    virtual:
      enabled: false

server:
  port: ${SERVER_PORT:8080}
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}